### ISSUE TITLE
Simple dice roller not working with DnD 5e UI

### ISSUE THREAD

**Issue by zimm44** [jopeek/fvtt-simple-dice-roller#13]
Breaks when used together with Dnd 5e ui mod, happening only at v9.

![dnd 5e ui](https://user-images.githubusercontent.com/67938397/147262551-cc7b3766-e951-4b56-b9e8-3e4e439b773f.png)

**Comment by jopeek** [comment]
That’s not surprising, but I’ll check it out and see if I can tweak my css to make it work with this other mod installed.

**Comment by jopeek** [comment]
Resolved this in 1.3.4.
