### ISSUE TITLE
[Bug] Menu does not open if closed without rolling dice

### ISSUE THREAD

**Issue by mrkwnzl** [jopeek/fvtt-simple-dice-roller#2]
The menu to select dice does not open again when I select another tool and then Simple Dice Roller.

**Steps to reproduce:**

1. Click on the Simple Dice Roller icon in the menu bar. The menu to select the dice opens.
2. Click on the Basic Controls icon.
3. Click on the Simple Dice Roller icon again. The menu to select the dice does not open.

**Setup:**

OS: macOS 10.5.6
Foundry: 0.6.6
Simple Dice Roller: 1.1.0

No other modules were active for testing.

**Comment by jopeek** [comment]
Confirmed. Will be fixed soon.
